from __future__ import annotations

import shlex
from datetime import datetime, timezone
from pathlib import Path

from signalstripper import __version__
from signalstripper.analyze import GlobalSummary
from signalstripper.select import SelectionSet, estimate_reclaim, to_cli_args


def _human_bytes(n: int) -> str:
    """Format a byte count with the same decimal (SI) convention as the web
    UI's fmtBytes() in static/app.js, so the estimate printed in the emitted
    command matches the on-screen reclaim tally exactly."""
    if not n:
        return "0 B"
    if n >= 1_000_000_000:
        return f"{n / 1e9:.2f} GB"
    if n >= 1_000_000:
        return f"{n / 1e6:.1f} MB"
    if n >= 1_000:
        return f"{n / 1e3:.0f} KB"
    return f"{n} B"


def emit_reclaim_command(
    db_path: Path,
    output_path: Path,
    selection: SelectionSet,
    summary: GlobalSummary,
    signalbackup_tools_path: Path = Path("vendor/signalbackup-tools/signalbackup-tools"),
) -> str:
    estimated_bytes = estimate_reclaim(selection, summary)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    args = to_cli_args(selection, summary)
    cmd_parts = [
        shlex.quote(str(signalbackup_tools_path)),
        shlex.quote(str(db_path)),
        "--output", shlex.quote(str(output_path)),
    ] + [shlex.quote(a) if not a.startswith("--") else a for a in args]

    cmd = " \\\n    ".join(cmd_parts)

    return (
        f"# Generated by signalstripper {__version__} on {date_str}\n"
        f"# Estimated reclaim: ~{_human_bytes(estimated_bytes)}\n"
        f"# Review carefully and run manually. signalstripper never auto-runs this.\n"
        f"# Keep the original backup at {db_path} as a fallback until verified.\n"
        f"{cmd}\n"
    )
