from __future__ import annotations

import shlex
from datetime import datetime, timezone
from pathlib import Path

from signalstripper import __version__
from signalstripper.analyze import GlobalSummary
from signalstripper.select import SelectionSet, estimate_reclaim, to_cli_args


def emit_reclaim_command(
    db_path: Path,
    output_path: Path,
    selection: SelectionSet,
    summary: GlobalSummary,
    signalbackup_tools_path: Path = Path("vendor/signalbackup-tools/signalbackup-tools"),
) -> str:
    estimated_bytes = estimate_reclaim(selection, summary)
    estimated_gb = estimated_bytes / 1024**3
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    args = to_cli_args(selection, summary)
    cmd_parts = [
        shlex.quote(str(signalbackup_tools_path)),
        shlex.quote(str(db_path)),
        "--output", shlex.quote(str(output_path)),
    ] + [shlex.quote(a) if not a.startswith("--") else a for a in args]

    cmd = " \\\n    ".join(cmd_parts)

    return (
        f"# Generated by signalstripper {__version__} on {date_str}\n"
        f"# Estimated reclaim: ~{estimated_gb:.2f} GB\n"
        f"# Review carefully and run manually. signalstripper never auto-runs this.\n"
        f"# Keep the original backup at {db_path} as a fallback until verified.\n"
        f"{cmd}\n"
    )
